# Generated by Django 3.2.8 on 2021-11-03 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('score1', models.IntegerField(default=25000)),
                ('score2', models.IntegerField(default=25000)),
                ('score3', models.IntegerField(default=25000)),
                ('socre4', models.IntegerField(default=25000)),
                ('ranking1', models.PositiveSmallIntegerField(default=0)),
                ('ranking2', models.PositiveSmallIntegerField(default=0)),
                ('ranking3', models.PositiveSmallIntegerField(default=0)),
                ('ranking4', models.PositiveSmallIntegerField(default=0)),
                ('player1', models.ForeignKey(default='Unknown Player', on_delete=django.db.models.deletion.CASCADE, related_name='first_player', to='games.player')),
                ('player2', models.ForeignKey(default='Unknown Player', on_delete=django.db.models.deletion.CASCADE, related_name='second_player', to='games.player')),
                ('player3', models.ForeignKey(default='Unknown Player', on_delete=django.db.models.deletion.CASCADE, related_name='third_player', to='games.player')),
                ('player4', models.ForeignKey(default='Unknown Player', on_delete=django.db.models.deletion.CASCADE, related_name='fourth_player', to='games.player')),
            ],
        ),
    ]
