# Generated by Django 3.2.8 on 2021-11-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='game',
            name='ranking1',
            field=models.CharField(choices=[('first_place', '一位'), ('second_place', '二位'), ('third_place', '三位'), ('fourth_place', '四位')], default='一位', max_length=16),
        ),
        migrations.AlterField(
            model_name='game',
            name='ranking2',
            field=models.CharField(choices=[('first_place', '一位'), ('second_place', '二位'), ('third_place', '三位'), ('fourth_place', '四位')], default='二位', max_length=16),
        ),
        migrations.AlterField(
            model_name='game',
            name='ranking3',
            field=models.CharField(choices=[('first_place', '一位'), ('second_place', '二位'), ('third_place', '三位'), ('fourth_place', '四位')], default='三位', max_length=16),
        ),
        migrations.AlterField(
            model_name='game',
            name='ranking4',
            field=models.CharField(choices=[('first_place', '一位'), ('second_place', '二位'), ('third_place', '三位'), ('fourth_place', '四位')], default='四位', max_length=16),
        ),
    ]
