# Generated by Django 3.2.8 on 2022-01-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20220117_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='socre4',
        ),
        migrations.AddField(
            model_name='game',
            name='score4',
            field=models.IntegerField(default=25000, verbose_name='四位分数'),
        ),
        migrations.AlterField(
            model_name='game',
            name='score1',
            field=models.IntegerField(default=25000, verbose_name='一位分数'),
        ),
        migrations.AlterField(
            model_name='game',
            name='score2',
            field=models.IntegerField(default=25000, verbose_name='二位分数'),
        ),
        migrations.AlterField(
            model_name='game',
            name='score3',
            field=models.IntegerField(default=25000, verbose_name='三位分数'),
        ),
    ]
